export * from './crud/crud.controller';
export * from './crud/crud.dto';
export * from './crud/crud.interface';
export * from './crud/crud.functions';
export * from './watch/watch-value.entity';
export * from './watch/watch-float-value.entity';
export * from './watch/watch-int-value.entity';
export * from './watch/watch-label';
export * from './watch/watch.subscriber';
export * from './watch/watch.interface';
export * from './auth/auth.module';
export * from './auth/guards/jwt.guard';
export * from './auth/guards/local.guard';
export * from './entities/user-data.entity';
export * from './helpers/bull.helper';
export * from './helpers/handy.helpers';
export * from './mail/mail.module';
export * from './viewer/viewer.controller';
export * from './main.helpers';
export * from './entities/email-validation.entity';
import { UserAvatarEntity } from './entities/user-avatar.entity';
export const UserEntity = UserAvatarEntity;
